### PR TITLE
Improved Slack notifications

### PR DESCRIPTION
**Pull request by elblivion**
New SHA512: 01bd0cd5d243e7498f64321ba25e18158e182f0ad5de879eb700a0578c14b6ae8a2a35e57b8b9fa2c387e6be431bb9a6fbde2822bdce61ec4182025772ca037e

### CODE REVIEW

**Comment by elblivion** [comment]
image


image

**Comment by danihodovic** [comment]
Very nice. Is it still possible to keep the commit sha?

**Comment by elblivion** [comment]
What do you mean? For production? The SHA would be different because it's a merge commit. Remember `cf-mypackage.deb` actually is the package name with version number included, which includes the commit SHA.

**Comment by danihodovic** [comment]
What I'm saying is this: is there a way for me to find what git commit the debian package corresponds to?

**Comment by elblivion** [comment]
Like this?

image

**Comment by danihodovic** [comment]
Bueno

**Comment by elblivion** [comment]
You want the whole 40, or what? Still don't get it 😞

**Comment by benben** [comment]
i think he also wants it in the promotion message?!

**Comment by danihodovic** [comment]
> i think he also wants it in the promotion message?!

Would be nice. I'm also OK with how it is right now.

**Comment by benben** [comment]
LRGTM

**Pull request merged**
