### PR TITLE
Rename, add more docs

### PR DESCRIPTION
**Pull request by elblivion**
MD preview at: https://github.com/contentful/estivador/blob/rename/README.md

### CODE REVIEW

**Comment by danihodovic** [comment]
Very nice

**Comment by danihodovic** [comment]
Might want to add a description to the GH repo as well

**Comment by danihodovic** [comment]
Also instructions on md5'ing the script are welcome

**Comment by benben** [comment]
should we also mention something explicitlz about the promoting part and that we safe one CI run with this?

**Comment by elblivion** [comment]
Added bits about checksumming (in use in https://github.com/contentful/traffic-management/tree/pin-deploy-script, https://github.com/contentful/traffic-management/pull/23) and package promotion

**Pull request merged**
