### PR TITLE
Reformat notifications

### PR DESCRIPTION
**Pull request by elblivion**
HAPPY NOW??!!

New checksum b3c5bb9feb4d51561733e7b54ab47dafb87171d468947d837cdaf521fa16394e3711f29fe2e92ff56f374ffcd8920d3dd4c41a3bc11889894f8ab826bce87d8b

This adapts the messages to not wrap text (package add/package promote messages):

image

Whereas currently the messages are sort of like:

(Adding a package)

image

(promoting a package)

image

Icon and bot name remain as today:

image

### CODE REVIEW

**Comment by elblivion** [comment]
Checksum doesn't match because that's mocked copy & pasted.

**Comment by benben** [comment]
die kleinen freuden des jungen A.S. LGTM

**Comment by danihodovic** [comment]
Can you post the difference before and after?

**Comment by elblivion** [comment]
Updated the description

**Comment by danihodovic** [comment]
If this is before
https://cloud.githubusercontent.com/assets/2480211/15932923/e26bc62c-2e5d-11e6-9119-feef4ac8ad96.png
and this is after
https://cloud.githubusercontent.com/assets/2480211/15932957/08499d1a-2e5e-11e6-9b02-90c124e55384.png

I prefer before :dancer:

**Comment by elblivion** [comment]
Updated the description again

**Comment by danihodovic** [comment]
# lgtm

**Pull request merged**
